version: "3"

services:
  nginx:
    image: "nginx:1.10"
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - nodejs
  nodejs:
    image: "node:6.10-wheezy"
    volumes:
      - ./server.js:/server.js
    command: [ /usr/bin/env, node, /server.js ]
